
 document.write("<div id='cover' >")

 document.write("<div class='wrapper z-index:2;' id='load'>");
   document.write( "<div class='line line1'>");
      document.write("<span class='circle circle-top'></span>")
	  
      document.write("<div class='dotted'>")
	  
      document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line2'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line3'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line4'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line5'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line6'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line7'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line8'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
      document.write(" <span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line9'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line10'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
     document.write("<div class='line line11'>")
       document.write("<span class='circle circle-top'></span>")
       document.write("<div class='dotted'>")
         document.write("<span class='dot dot-top'></span>")
         document.write("<span class='dot dot-middle-top'></span>")
         document.write("<span class='dot dot-middle-bottom'></span>")
         document.write("<span class='dot dot-bottom'></span>")
       document.write("</div>")
       document.write("<span class='circle circle-bottom'></span>")
     document.write("</div>")
   document.write("</div>")
  document.write("</div>")

  